id: tabletop_laptop_open
objects:
  table:
    asset: maniskill:table
    category: workspace
    description: 木质餐桌
    static: true
    pose: [0, 0, 0, 0, 0, 0, 1]
  laptop:
    asset: robodojo:laptop_fixed
    category: articulated_object
    description: 固定底座且屏幕已打开的笔记本电脑
    static: false
    pose: [0.12, -0.28, 0, 0, 0, -0.7071067811865475, 0.7071067811865476]
    joint_positions:
      RevoluteJoint_computer_9_up: -1.6580627893946132
parameters:
  workspace_pose: [0.45, 0, 0.75, 0, 0, 0, 1]
  workspace_size: [0.96, 1.9]
