id: tabletop_objects
objects:
  table:
    asset: maniskill:table
    category: workspace
    description: 木质餐桌
    static: true
    pose:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
  object:
    asset: robodojo:brick
    category: graspable_object
    description: 红色积木
    static: false
    pose:
    - -0.05
    - -0.1
    - 0.0172
    - 0
    - 0
    - 0
    - 1
    position_min:
    - -0.07
    - -0.12
    position_max:
    - -0.02
    - -0.05
  basket:
    asset: robodojo:basket
    category: receptacle
    description: 灰色收纳篮
    static: false
    pose:
    - 0.13
    - 0.12
    - 0.03857
    - 0
    - 0
    - 0
    - 1
parameters:
  workspace_pose:
  - 0.45
  - 0
  - 0.75
  - 0
  - 0
  - 0
  - 1
  workspace_size:
  - 0.96
  - 1.9
