id: tabletop_push_varied
objects:
  table:
    asset: maniskill:table
    category: workspace
    description: 木质餐桌
    static: true
    pose: [0, 0, 0, 0, 0, 0, 1]
  object:
    asset: robodojo:brick
    category: graspable_object
    description: 红色积木
    static: false
    pose: [-0.05, -0.10, 0.0172, 0, 0, 0, 1]
    position_min: [-0.06, -0.105]
    position_max: [-0.04, -0.095]
parameters:
  workspace_pose: [0.45, 0, 0.75, 0, 0, 0, 1]
  workspace_size: [0.96, 1.9]
