id: tabletop_tea_carton_pack_yaw15
objects:
  table:
    asset: maniskill:table
    category: workspace
    description: 木质餐桌
    static: true
    pose: [0, 0, 0, 0, 0, 0, 1]
  tea_pack:
    asset: robodojo:tea_carton_pack
    category: graspable_object
    description: 绿白色六盒茶饮包装
    static: false
    pose: [0, 0, 0.0411, 0, 0, 0.7933533403, 0.608761429]
parameters:
  workspace_pose: [0.45, 0, 0.75, 0, 0, 0, 1]
  workspace_size: [0.96, 1.9]
