id: tabletop_push_yaw_positive
objects:
  table:
    asset: maniskill:table
    category: workspace
    description: 木质餐桌
    static: true
    pose: [0, 0, 0, 0, 0, 0, 1]
  object:
    asset: robodojo:brick
    category: graspable_object
    description: 红色积木
    static: false
    pose: [-0.05, -0.10, 0.0172, 0, 0, 0.17364817766693033, 0.984807753012208]
parameters:
  workspace_pose: [0.45, 0, 0.75, 0, 0, 0, 1]
  workspace_size: [0.96, 1.9]
